{python37Packages,...}: python37Packages.buildPythonPackage rec {
  pname = "GamestonkTerminal";
  version = "git";
  src = ./GamestonkTerminal;
  doCheck = false;
  propagatedBuildInputs = with python37Packages; [
    #TimeSeriesCrossValidation @ git+https://github.com/DidierRLopes/TimeSeriesCrossValidation@1e29d393204abb3bde23ff3f15258ed85d3b263e
    #FundamentalAnalysis
    #Janome
    #alpha-vantage
    #appscript
    #bpemb
    #config
    #fbprophet
    #finviz
    #flair
    #flatbuffers
    #google-auth
    #hijri-converter
    #hyperopt
    #konoha
    #levenshtein
    #lunarcalendar
    #mpld3
    #overrides
    #pandas-ta
    #pmdarima
    #psaw
    #rapidfuzz
    #requests-oauthlib
    #scikit-learn
    #segtok
    #smart-open
    #tensorboard-plugin-wit
    #update-checker
    #user-agent
    #websocket-client
    #xlwings
    #yahoo-fin
    Keras#-Preprocessing
    Quandl
    XlsxWriter
    absl-py
    aiohttp
    aiohttp
    astunparse
    async-timeout
    attrs
    beautifulsoup4
    beautifulsoup4
    cachetools
    certifi
    chardet
    click
    cloudpickle
    convertdate
    cssselect
    cycler
    cython
    dateutil
    decorator
    deprecated
    filelock
    ftfy
    future
    gast
    gdown
    gensim
    google-auth-oauthlib
    google-pasta
    grpcio
    h5py
    holidays
    idna
    importlib-metadata
    inflection
    iso8601
    joblib
    kiwisolver
    korean-lunar-calendar
    langdetect
    lxml
    markdown
    matplotlib
    more-itertools
    multidict
    multitasking
    networkx
    numpy
    oauthlib
    opt-einsum
    packaging
    pandas
    patsy
    praw
    prawcore
    prettytable
    protobuf
    psutil
    pyasn1
    pyasn1-modules
    pymeeus
    pyparsing
    pysocks
    python-dateutil
    pytorch
    pytrends
    pytz
    regex
    requests
    rsa
    sacremoses
    scipy
    sentencepiece
    six
    soupsieve
    sqlitedict
    statsmodels
    tabulate
    tensorflow-bin_2
    tensorflow-estimator_2
    tensorflow-tensorboard_2
    termcolor
    threadpoolctl
    tokenizers
    tqdm
    transformers
    typing-extensions
    urllib3
    wcwidth
    werkzeug
    wrapt
    yarl
    yfinance
    zipp
  ];
}
